apiVersion: v1
kind: PersistentVolume
metadata:
  name: k3s-pv-worker11
spec:
  capacity:
    storage: 150Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: weights
  local:
    path: /shared/bin
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker11